"""Store interface: registry, plans, per-site locks, audit."""

from __future__ import annotations

from typing import Protocol

from ..models import AuditEntry, Plan, Site


class Store(Protocol):
    # --- registry ---
    def list_sites(self, filter: str | None = None) -> list[Site]: ...
    def get_site(self, slug: str) -> Site | None: ...
    def upsert_site(self, site: Site) -> None: ...

    # --- plans ---
    def create_plan(self, plan: Plan) -> None: ...
    def get_plan(self, plan_id: str) -> Plan | None: ...
    def update_plan(self, plan: Plan) -> None: ...

    # --- per-site lock (serialize writes across plan->apply) ---
    def try_acquire_lock(self, site: str, holder: str) -> bool: ...
    def release_lock(self, site: str, holder: str) -> None: ...

    # --- audit ---
    def record_audit(self, entry: AuditEntry) -> None: ...
    def recent_audit(self, site: str | None = None, limit: int = 50) -> list[AuditEntry]: ...
